In [26]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer
import seaborn as sns

In [27]:
df = pd.read_csv('CAR DETAILS FROM CAR DEKHO.csv')
df.head(5)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [28]:
df.drop("seller_type",axis =1,inplace=True)
df.head(5)

,name,year,selling_price,km_driven,fuel,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Manual,Second Owner

In [29]:
df.shape

(4340, 7)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   transmission   4340 non-null   object
 6   owner          4340 non-null   object
dtypes: int64(3), object(4)
memory usage: 237.5+ KB

In [31]:
df['year'].unique()

array([2007, 2012, 2017, 2014, 2016, 2015, 2018, 2019, 2013, 2011, 2010,
       2009, 2006, 1996, 2005, 2008, 2004, 1998, 2003, 2002, 2020, 2000,
       1999, 2001, 1995, 1997, 1992], dtype=int64)

In [32]:
df.drop("owner",axis =1,inplace=True)
df.head(5)

,name,year,selling_price,km_driven,fuel,transmission
0,Maruti 800 AC,2007,60000,70000,Petrol,Manual
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Manual
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Manual
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Manual
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Manual

In [33]:
df.describe()

              year  selling_price      km_driven
count  4340.000000   4.340000e+03    4340.000000
mean   2013.090783   5.041273e+05   66215.777419
std       4.215344   5.785487e+05   46644.102194
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.087498e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

In [34]:
df.to_csv('Cleaned Data.csv')

In [35]:
X = df.drop(columns='selling_price')
Y = df['selling_price']
print(X)
print(Y)

                                     name  year  km_driven    fuel  \
0                           Maruti 800 AC  2007      70000  Petrol
1                Maruti Wagon R LXI Minor  2007      50000  Petrol
2                    Hyundai Verna 1.6 SX  2012     100000  Diesel
3                  Datsun RediGO T Option  2017      46000  Petrol
4                   Honda Amaze VX i-DTEC  2014     141000  Diesel
...                                   ...   ...        ...     ...
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014      80000  Diesel
4336           Hyundai i20 Magna 1.4 CRDi  2014      80000  Diesel
4337                  Maruti 800 AC BSIII  2009      83000  Petrol
4338     Hyundai Creta 1.6 CRDi SX Option  2016      90000  Diesel
4339                     Renault KWID RXT  2016      40000  Petrol

     transmission
0          Manual
1          Manual
2          Manual
3          Manual
4          Manual
...           ...
4335       Manual
4336       Manual
4337       Manual
4338       Manual
4339       Manual

[4340 rows x 5 columns]
0        60000
1       135000
2       600000
3       250000
4       450000
         ...
4335    409999
4336    409999
4337    110000
4338    865000
4339    225000
Name: selling_price, Length: 4340, dtype: int64

In [36]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=2)
print(X_train)
print(X_test)

                                         name  year  km_driven    fuel  \
3581         Volkswagen Ameo 1.5 TDI Highline  2017      70000  Diesel
4191  Mahindra Scorpio VLX 2WD AIRBAG SE BSIV  2012      72000  Diesel
2450                  Maruti Ciaz 1.4 AT Zeta  2017      40000  Petrol
984         Fiat Grande Punto EVO 1.3 Dynamic  2014      70000  Diesel
3546                     Maruti Swift 1.2 DLX  2018      35000  Petrol
...                                       ...   ...        ...     ...
3335         Hyundai Grand i10 1.2 Kappa Asta  2018      32000  Petrol
1099                     Honda City i DTEC VX  2014     110000  Diesel
2514      Hyundai i20 Magna Optional 1.4 CRDi  2013      50000  Diesel
3606                         Mahindra Xylo D2  2010      70000  Diesel
2575                      Datsun RediGO 1.0 S  2017      15000  Petrol

     transmission
3581       Manual
4191       Manual
2450    Automatic
984        Manual
3546       Manual
...           ...
3335       Manual
1099       Manual
2514       Manual
3606       Manual
2575       Manual

[3472 rows x 5 columns]
                             name  year  km_driven    fuel transmission
1149              Maruti Ciaz ZXi  2016      30000  Petrol       Manual
2245   Hyundai Grand i10 Magna AT  2017      10510  Petrol    Automatic
4261  Tata Sumo GX TC 7 Str BSIII  2006     100000  Diesel       Manual
2865    Volvo XC60 D5 Inscription  2014     130000  Diesel    Automatic
3110        Mahindra Scorpio BSIV  2018      60000  Diesel       Manual
...                           ...   ...        ...     ...          ...
2168                 Tata Sumo LX  2009      66778  Diesel       Manual
3783              Audi A6 2.8 FSI  2008      70000  Petrol    Automatic
1683       Maruti Swift Dzire LDI  2015      73000  Diesel       Manual
2420     Hyundai EON 1.0 Era Plus  2018      21302  Petrol       Manual
3354       Hyundai EON Magna Plus  2018      20000  Petrol       Manual

[868 rows x 5 columns]

In [39]:
import pandas as pd
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import make_pipeline

# Convert X_train and X_test to DataFrame if they are not already
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

# Create the column transformer with SimpleImputer and OneHotEncoder
column_trans = make_column_transformer(
    (make_pipeline(SimpleImputer(strategy='constant', fill_value='missing'), OneHotEncoder(handle_unknown='ignore')), 
     ['name', 'fuel', 'transmission']),
    remainder='passthrough'
)

# Transform the data
X_train_transformed = column_trans.fit_transform(X_train)
X_test_transformed = column_trans.transform(X_test)

# Verify transformation by checking the shape of transformed data
print("Shape of X_train_transformed:", X_train_transformed.shape)
print("Shape of X_test_transformed:", X_test_transformed.shape)

# Optionally, create a DataFrame to see the transformed columns
transformed_feature_names = column_trans.get_feature_names_out()
X_train_transformed_df = pd.DataFrame(X_train_transformed.toarray(), columns=transformed_feature_names)
X_test_transformed_df = pd.DataFrame(X_test_transformed.toarray(), columns=transformed_feature_names)

print("Transformed X_train DataFrame:\n", X_train_transformed_df.head())
print("Transformed X_test DataFrame:\n", X_test_transformed_df.head())

# Create the pipeline
pipeline = make_pipeline(
    column_trans,
    RandomForestRegressor()
)

# Train the model
pipeline.fit(X_train, Y_train)

# Make predictions
Y_pred = pipeline.predict(X_test)

print("Predictions:", Y_pred)

Shape of X_train_transformed: (3472, 1342)
Shape of X_test_transformed: (868, 1342)
Transformed X_train DataFrame:
    pipeline__name_Ambassador CLASSIC 1500 DSL AC  \
0                                            0.0
1                                            0.0
2                                            0.0
3                                            0.0
4                                            0.0

   pipeline__name_Ambassador Classic 2000 Dsz  \
0                                         0.0
1                                         0.0
2                                         0.0
3                                         0.0
4                                         0.0

   pipeline__name_Ambassador Grand 1800 ISZ MPFI PW CL  \
0                                                0.0
1                                                0.0
2                                                0.0
3                                                0.0
4                                                0.0

   pipeline__name_Audi A4 2.0 TDI 177 Bhp Premium Plus  \
0                                                0.0
1                                                0.0
2                                                0.0
3                                                0.0
4                                                0.0

   pipeline__name_Audi A4 3.0 TDI Quattro  \
0                                     0.0
1                                     0.0
2                                     0.0
3                                     0.0
4                                     0.0

   pipeline__name_Audi A4 30 TFSI Technology  \
0                                        0.0
1                                        0.0
2                                        0.0
3                                        0.0
4                                        0.0

   pipeline__name_Audi A4 35 TDI Premium  \
0                                    0.0
1                                    0.0
2                                    0.0
3                                    0.0
4                                    0.0

   pipeline__name_Audi A4 35 TDI Premium Plus  \
0                                         0.0
1                                         0.0
2                                         0.0
3                                         0.0
4                                         0.0

   pipeline__name_Audi A4 New  2.0 TDI Multitronic  \
0                                              0.0
1                                              0.0
2                                              0.0
3                                              0.0
4                                              0.0

   pipeline__name_Audi A5 Sportback  ...  \
0                               0.0  ...
1                               0.0  ...
2                               0.0  ...
3                               0.0  ...
4                               0.0  ...

   pipeline__name_Volvo XC60 D3 Kinetic  pipeline__fuel_CNG  \
0                                   0.0                 0.0
1                                   0.0                 0.0
2                                   0.0                 0.0
3                                   0.0                 0.0
4                                   0.0                 0.0

   pipeline__fuel_Diesel  pipeline__fuel_Electric  pipeline__fuel_LPG  \
0                    1.0                      0.0                 0.0
1                    1.0                      0.0                 0.0
2                    0.0                      0.0                 0.0
3                    1.0                      0.0                 0.0
4                    0.0                      0.0                 0.0

   pipeline__fuel_Petrol  pipeline__transmission_Automatic  \
0                    0.0                               0.0
1                    0.0                               0.0
2                    1.0                               1.0
3                    0.0                               0.0
4                    1.0                               0.0

   pipeline__transmission_Manual  remainder__year  remainder__km_driven
0                            1.0           2017.0               70000.0
1                            1.0           2012.0               72000.0
2                            0.0           2017.0               40000.0
3                            1.0           2014.0               70000.0
4                            1.0           2018.0               35000.0

[5 rows x 1342 columns]
Transformed X_test DataFrame:
    pipeline__name_Ambassador CLASSIC 1500 DSL AC  \
0                                            0.0
1                                            0.0
2                                            0.0
3                                            0.0
4                                            0.0

   pipeline__name_Ambassador Classic 2000 Dsz  \
0                                         0.0
1                                         0.0
2                                         0.0
3                                         0.0
4                                         0.0

   pipeline__name_Ambassador Grand 1800 ISZ MPFI PW CL  \
0                                                0.0
1                                                0.0
2                                                0.0
3                                                0.0
4                                                0.0

   pipeline__name_Audi A4 2.0 TDI 177 Bhp Premium Plus  \
0                                                0.0
1                                                0.0
2                                                0.0
3                                                0.0
4                                                0.0

   pipeline__name_Audi A4 3.0 TDI Quattro  \
0                                     0.0
1                                     0.0
2                                     0.0
3                                     0.0
4                                     0.0

   pipeline__name_Audi A4 30 TFSI Technology  \
0                                        0.0
1                                        0.0
2                                        0.0
3                                        0.0
4                                        0.0

   pipeline__name_Audi A4 35 TDI Premium  \
0                                    0.0
1                                    0.0
2                                    0.0
3                                    0.0
4                                    0.0

   pipeline__name_Audi A4 35 TDI Premium Plus  \
0                                         0.0
1                                         0.0
2                                         0.0
3                                         0.0
4                                         0.0

   pipeline__name_Audi A4 New  2.0 TDI Multitronic  \
0                                              0.0
1                                              0.0
2                                              0.0
3                                              0.0
4                                              0.0

   pipeline__name_Audi A5 Sportback  ...  \
0                               0.0  ...
1                               0.0  ...
2                               0.0  ...
3                               0.0  ...
4                               0.0  ...

   pipeline__name_Volvo XC60 D3 Kinetic  pipeline__fuel_CNG  \
0                                   0.0                 0.0
1                                   0.0                 0.0
2                                   0.0                 0.0
3                                   0.0                 0.0
4                                   0.0                 0.0

   pipeline__fuel_Diesel  pipeline__fuel_Electric  pipeline__fuel_LPG  \
0                    0.0                      0.0                 0.0
1                    0.0                      0.0                 0.0
2                    1.0                      0.0                 0.0
3                    1.0                      0.0                 0.0
4                    1.0                      0.0                 0.0

   pipeline__fuel_Petrol  pipeline__transmission_Automatic  \
0                    1.0                               0.0
1                    1.0                               1.0
2                    0.0                               0.0
3                    0.0                               1.0
4                    0.0                               0.0

   pipeline__transmission_Manual  remainder__year  remainder__km_driven
0                            1.0           2016.0               30000.0
1                            0.0           2017.0               10510.0
2                            1.0           2006.0              100000.0
3                            0.0           2014.0              130000.0
4                            1.0           2018.0               60000.0

[5 rows x 1342 columns]
Predictions: [ 635600.          520000.          112289.11       1583370.
  770090.          402300.          274140.           83147.5
  229999.          371990.          273784.93        221619.99
  568649.99        470029.92         76750.         1573649.99
  299823.32333333  458120.          541899.99        352099.81
  372729.99        208550.          186780.          389910.
 2502090.          390373.33333333 1671269.97        452210.
  197279.98        392329.97        346300.          112625.
  672899.99        298446.61666667   80000.          541899.99
  304999.93        175679.71        964549.99        463583.32333333
  809724.98        705730.         1619970.          595149.99
 2600000.          242033.26333333  508040.          522509.98
  485542.426       250945.          464729.38        315459.98
  490500.          608969.98        240100.          225000.
  452883.33333333  483850.          332133.33333333  511749.91
  736449.99        548439.78        287810.          786009.6
  254158.56047619   78957.14285714  239000.          167002.46
  239000.          593187.49        191079.88        233090.
  329990.          480919.85        874758.29333333  224910.
  377497.44        444171.65166667  520000.          462139.83
  649729.95        655430.          555650.          661789.98
  201469.96        202750.          267341.64666667  515819.97
 1671549.99        625000.          423919.92        140487.46
  292551.62666667  652080.         1950059.96        321959.92
 1085700.          210129.97        462520.          206830.
  860799.69         73496.66666667  452210.          304013.33333333
  242719.78        197625.83333333  816569.45        301969.9
  184760.          636599.98        429150.         2600000.
  267341.64666667  426050.          237359.98        220593.33333333
  679623.32333333  755550.          263850.          225000.
  480239.98        635600.          252512.37891775  883089.99
  379829.99        330669.99        343360.          240980.
  217540.          944350.          249681.46666667  463860.
  822610.          449890.          750000.          455410.
  113549.85        173025.54555556  900469.98        496079.9
  258420.          760000.          117687.5         434029.9
  521889.91        376450.          280349.99        673350.
  137575.          272799.97        552519.6         855093.29333333
  635933.33333333  540299.93         65970.          491029.99
  258450.          212620.          445218.29816667  450549.98
  668430.          799620.         2185149.99        408189.99
  399106.47666667  528950.          499629.93        791610.
  532269.93        472354.94        255220.          494449.96
  241520.          657840.          716379.7         250300.
  759260.          197769.97        239369.87        573860.
  130300.          283700.          742130.          668400.
  471449.8         503216.66666667  652180.          544209.98
  185300.          407439.99        210740.          236559.99
  308099.94        241900.          255400.          550000.
  179698.32333333  346015.           95638.          244209.76
  730525.          277279.96        146539.97        756280.
  224049.99        167300.         1734694.16666667  417350.
  240099.99        699390.          199825.         1507149.99
  776249.98        304270.          309719.97        178049.99
  204079.99        187183.33333333   96970.          480779.93
  119247.96        808875.          155799.82        187975.
  583553.33333333  262949.96        201760.         1053779.99
  178517.24        389249.88        196569.97       1414239.96
   97148.33333333  125880.          520000.          161199.97
 1663050.          469599.99        328329.98        369066.66666667
  318976.66666667  880261.63666667  329750.          183669.99
  230950.          228660.          342030.          328939.97
  278041.65666667 1083710.          173094.961       276304.91
  428869.92        313753.33333333  338791.66666667 4950000.
  321959.92         88983.33333333  200249.946        87840.
 1286829.99        182770.          287039.98         99330.
  263229.12666667  614149.99        161740.52447619  603163.32333333
  143850.          593190.          639429.16666667  255251.74463203
  142519.99        280367.49        486040.          489519.96
   92240.          571059.99        247650.          229999.
  217716.66666667  477379.99        243870.34333333 1355680.
 3038810.          442049.99        786379.83        571669.98
  450000.          465360.          258874.995       171790.83333333
  254920.          136300.          344699.96        321959.92
  828769.74         78957.14285714  126959.99        402349.97
  201635.          314550.          304813.33333333  101021.66666667
  403966.66666667  103110.          274140.          670000.
   71971.66666667  512989.94        258724.94        361559.96
   54765.          125480.          267723.30333333  434870.
   75730.         2319550.          224910.          151849.99
  183700.         1580000.          239789.84        264093.24666667
 1750559.87        785653.29333333 2245180.          501570.
  226075.          261204.86        725850.          576692.85714286
  170159.88        156421.65666667  227200.          356383.27333333
  750000.          160366.64666667  120000.          286249.98
  233916.56666667  166159.97        325789.96        168810.
  238999.89        386030.          591500.         1023600.
 1454690.          204750.          164250.          700139.97
  377497.44        385000.          736993.31333333 1300000.
   64925.          464000.          156421.65666667  263600.
  313790.          643443.33333333  385000.          452034.98
  155041.66666667   70755.          392730.          766439.94
  247009.85        399460.          606319.52380952  129050.
  242719.78         53885.          462520.          293800.
 1580000.          266947.23033333  626050.          816569.45
  276098.33333333  418310.          217968.33333333  447819.98
  261370.          164359.99        145019.97        250949.98
   98539.96        470822.4735      253071.54666667  683633.32333333
   79530.          342629.96        310850.          752799.97
  172359.95        458380.          496079.9         202419.99
  442083.19333333  110440.          525389.97        342750.
  885143.27333333   93900.          300849.98        440239.6
  357500.         1269894.16666667  314634.97        130328.91
  512209.99        469629.99        429830.          776949.98
  248120.          389780.          342750.          107650.
  245084.97        262703.33333333  100500.          731162.15
  308400.          625000.           99149.99        417004.94
  255910.          828863.15333333  321950.          276219.96
  384560.          742440.          801140.          281249.96
  499899.97         88823.33333333  272460.          216149.71
  623929.91        364300.          388059.99        477379.99
  648449.96        241051.66666667  419860.          494089.97
  485789.99        104660.          275789.99        124649.99
  433699.95        188130.          585199.94        248945.
  279389.94        781349.37        238160.          151199.94
  206576.54666667  439160.          187850.          252939.75
  241849.99        362203.8325      224239.99        139862.49
  357760.          270651.13047619  386450.          341249.95
  172300.         1412220.          474449.99        706928.33333333
  286405.          494249.99       2245180.         2900810.
  403800.         1673730.          218650.          809770.
  276161.43939394  121103.35666667  944618.27333333  279179.95
  304013.33333333  240873.30333333  518669.98        683633.32333333
   69380.83333333  717840.          192700.          104660.
  600000.          174899.98        160189.99        242424.88
  388740.          298164.71        249590.          490519.9
  117687.5         144984.985       332269.94        597510.
   75370.83333333 1531849.99        512400.          305900.
  423340.          656349.98        327149.81        145809.66
  236459.99        445600.          154999.96        125109.99
  187400.         1580000.          110440.          450549.98
  127161.11        491169.92        463499.98       1907456.66666667
  392939.94        262710.          297059.96        250864.73
  234593.33333333  860799.69        718099.99        263110.
  385000.           82448.33333333  203526.55666667  450000.
  424960.          236139.81        117780.          133200.
 2600000.          160189.99        506941.66666667  425433.28333333
  469049.99        197282.33666667  128497.80666667  450549.98
  604799.95        205081.99       1307530.           77805.
  121273.21428571   86042.          216650.          942160.
  184315.72333333  369950.          132969.99        321000.
  501053.33333333  292334.97        395410.          296299.99
  197625.83333333  220593.33333333  230024.23         86929.97
  393099.98        266033.12333333 1300000.          403966.66666667
  368350.          106066.66        304013.33333333  272770.
  488250.          132655.79333333 1690700.          246149.95
  266939.96        138090.81333333  503299.94        239560.69333333
  407450.          424499.86        477772.4735      457700.
  234969.93        164359.99        429549.96        852780.
  620899.94       1300000.          398200.          767089.84
  223809.94        446649.87        534059.99        583853.33333333
  252619.99        410069.93        246249.91         96288.33333333
  383559.99        150750.          462520.          125880.
  501660.          373949.71        690389.99        652080.
  459949.99        240910.          649899.95        825329.95
  634983.33333333  707090.          169965.          332539.96
  457350.          123250.          314550.          730088.33333333
  233736.66666667  764843.32333333  125880.          371759.985
  398916.66666667 3290400.         2779499.99        288159.99
  321810.          478600.          360940.          437823.33333333
  750000.          362119.95        322949.99        409110.
  670400.          535000.           92670.           82392.
  144838.64666667  229019.82        517900.          348193.31333333
  106350.          112234.79333333  440499.98        263610.
  198439.4         202138.28333333   97590.           93630.
  944910.          283034.98        808479.77        189469.99
 1197660.          478069.84        108099.85        417489.98
  838113.33333333  370119.9         234397.41        408479.94
  127813.33333333  493750.          941870.          455849.97
   69720.          230024.23        597697.89333333 1515290.
 1072900.          286269.96        460539.96        356650.
  224910.          423749.9         339963.33333333 1115560.
  309560.          494900.          161775.           63320.

In [42]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mae = mean_absolute_error(Y_test, Y_pred)
print("Mean Absolute Error (MAE):", mae)

mse = mean_squared_error(Y_test, Y_pred)
print("Mean Squared Error (MSE):", mse)

r2 = r2_score(Y_test, Y_pred)
print("R-squared (R²):", r2)

Mean Absolute Error (MAE): 114211.51064776134
Mean Squared Error (MSE): 65048036263.13385
R-squared (R²): 0.7998285586470039